[project]
name = "test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "ag-ui-protocol>=0.1.18",
    "botocore>=1.43.11", # Fixes an error about a missing module on startup
    "fastapi[standard]>=0.136.1",
    "litellm>=1.85.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.13",
]
